/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ActorsIndexRouteImport } from './routes/actors/index'
import { Route as ActorsSlugRouteImport } from './routes/actors/$slug'
import { Route as BollywoodIndexRouteImport } from './routes/bollywood/index'
import { Route as CricketIndexRouteImport } from './routes/cricket/index'
import { Route as CricketSlugRouteImport } from './routes/cricket/$slug'
import { Route as CricketPlayersRouteImport } from './routes/cricket/players'
import { Route as DramasIndexRouteImport } from './routes/dramas/index'
import { Route as DramasSlugRouteImport } from './routes/dramas/$slug'
import { Route as EntertainmentIndexRouteImport } from './routes/entertainment/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as MoviesSlugRouteImport } from './routes/movies/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as PslIndexRouteImport } from './routes/psl/index'
import { Route as PslDeskRouteImport } from './routes/psl/$desk'
import { Route as SportsIndexRouteImport } from './routes/sports/index'
import { Route as SportsFootballRouteImport } from './routes/sports/football'
import { Route as TalkOfTheTownIndexRouteImport } from './routes/talk-of-the-town/index'
import { Route as TalkOfTheTownSlugRouteImport } from './routes/talk-of-the-town/$slug'
import { Route as TalkOfTheTownPersonalitiesRouteImport } from './routes/talk-of-the-town/personalities'
import { Route as UpcomingDramasIndexRouteImport } from './routes/upcoming-dramas/index'
import { Route as UpcomingMoviesIndexRouteImport } from './routes/upcoming-movies/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/actors/',
  path: '/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsSlugRoute = ActorsSlugRouteImport.update({
  id: '/actors/$slug',
  path: '/actors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BollywoodIndexRoute = BollywoodIndexRouteImport.update({
  id: '/bollywood/',
  path: '/bollywood/',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketIndexRoute = CricketIndexRouteImport.update({
  id: '/cricket/',
  path: '/cricket/',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketSlugRoute = CricketSlugRouteImport.update({
  id: '/cricket/$slug',
  path: '/cricket/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketPlayersRoute = CricketPlayersRouteImport.update({
  id: '/cricket/players',
  path: '/cricket/players',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasIndexRoute = DramasIndexRouteImport.update({
  id: '/dramas/',
  path: '/dramas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasSlugRoute = DramasSlugRouteImport.update({
  id: '/dramas/$slug',
  path: '/dramas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentIndexRoute = EntertainmentIndexRouteImport.update({
  id: '/entertainment/',
  path: '/entertainment/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/movies/$slug',
  path: '/movies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PslIndexRoute = PslIndexRouteImport.update({
  id: '/psl/',
  path: '/psl/',
  getParentRoute: () => rootRouteImport,
} as any)
const PslDeskRoute = PslDeskRouteImport.update({
  id: '/psl/$desk',
  path: '/psl/$desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsFootballRoute = SportsFootballRouteImport.update({
  id: '/sports/football',
  path: '/sports/football',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkOfTheTownIndexRoute = TalkOfTheTownIndexRouteImport.update({
  id: '/talk-of-the-town/',
  path: '/talk-of-the-town/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkOfTheTownSlugRoute = TalkOfTheTownSlugRouteImport.update({
  id: '/talk-of-the-town/$slug',
  path: '/talk-of-the-town/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkOfTheTownPersonalitiesRoute =
  TalkOfTheTownPersonalitiesRouteImport.update({
    id: '/talk-of-the-town/personalities',
    path: '/talk-of-the-town/personalities',
    getParentRoute: () => rootRouteImport,
  } as any)
const UpcomingDramasIndexRoute = UpcomingDramasIndexRouteImport.update({
  id: '/upcoming-dramas/',
  path: '/upcoming-dramas/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingMoviesIndexRoute = UpcomingMoviesIndexRouteImport.update({
  id: '/upcoming-movies/',
  path: '/upcoming-movies/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/actors/$slug': typeof ActorsSlugRoute
  '/cricket/$slug': typeof CricketSlugRoute
  '/cricket/players': typeof CricketPlayersRoute
  '/dramas/$slug': typeof DramasSlugRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/psl/$desk': typeof PslDeskRoute
  '/sports/football': typeof SportsFootballRoute
  '/talk-of-the-town/$slug': typeof TalkOfTheTownSlugRoute
  '/talk-of-the-town/personalities': typeof TalkOfTheTownPersonalitiesRoute
  '/actors/': typeof ActorsIndexRoute
  '/bollywood/': typeof BollywoodIndexRoute
  '/cricket/': typeof CricketIndexRoute
  '/dramas/': typeof DramasIndexRoute
  '/entertainment/': typeof EntertainmentIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/psl/': typeof PslIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/talk-of-the-town/': typeof TalkOfTheTownIndexRoute
  '/upcoming-dramas/': typeof UpcomingDramasIndexRoute
  '/upcoming-movies/': typeof UpcomingMoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/actors/$slug': typeof ActorsSlugRoute
  '/cricket/$slug': typeof CricketSlugRoute
  '/cricket/players': typeof CricketPlayersRoute
  '/dramas/$slug': typeof DramasSlugRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/psl/$desk': typeof PslDeskRoute
  '/sports/football': typeof SportsFootballRoute
  '/talk-of-the-town/$slug': typeof TalkOfTheTownSlugRoute
  '/talk-of-the-town/personalities': typeof TalkOfTheTownPersonalitiesRoute
  '/actors': typeof ActorsIndexRoute
  '/bollywood': typeof BollywoodIndexRoute
  '/cricket': typeof CricketIndexRoute
  '/dramas': typeof DramasIndexRoute
  '/entertainment': typeof EntertainmentIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/news': typeof NewsIndexRoute
  '/psl': typeof PslIndexRoute
  '/sports': typeof SportsIndexRoute
  '/talk-of-the-town': typeof TalkOfTheTownIndexRoute
  '/upcoming-dramas': typeof UpcomingDramasIndexRoute
  '/upcoming-movies': typeof UpcomingMoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/actors/$slug': typeof ActorsSlugRoute
  '/cricket/$slug': typeof CricketSlugRoute
  '/cricket/players': typeof CricketPlayersRoute
  '/dramas/$slug': typeof DramasSlugRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/psl/$desk': typeof PslDeskRoute
  '/sports/football': typeof SportsFootballRoute
  '/talk-of-the-town/$slug': typeof TalkOfTheTownSlugRoute
  '/talk-of-the-town/personalities': typeof TalkOfTheTownPersonalitiesRoute
  '/actors/': typeof ActorsIndexRoute
  '/bollywood/': typeof BollywoodIndexRoute
  '/cricket/': typeof CricketIndexRoute
  '/dramas/': typeof DramasIndexRoute
  '/entertainment/': typeof EntertainmentIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/psl/': typeof PslIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/talk-of-the-town/': typeof TalkOfTheTownIndexRoute
  '/upcoming-dramas/': typeof UpcomingDramasIndexRoute
  '/upcoming-movies/': typeof UpcomingMoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/actors/$slug'
    | '/cricket/$slug'
    | '/cricket/players'
    | '/dramas/$slug'
    | '/movies/$slug'
    | '/news/$slug'
    | '/psl/$desk'
    | '/sports/football'
    | '/talk-of-the-town/$slug'
    | '/talk-of-the-town/personalities'
    | '/actors/'
    | '/bollywood/'
    | '/cricket/'
    | '/dramas/'
    | '/entertainment/'
    | '/movies/'
    | '/news/'
    | '/psl/'
    | '/sports/'
    | '/talk-of-the-town/'
    | '/upcoming-dramas/'
    | '/upcoming-movies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/actors/$slug'
    | '/cricket/$slug'
    | '/cricket/players'
    | '/dramas/$slug'
    | '/movies/$slug'
    | '/news/$slug'
    | '/psl/$desk'
    | '/sports/football'
    | '/talk-of-the-town/$slug'
    | '/talk-of-the-town/personalities'
    | '/actors'
    | '/bollywood'
    | '/cricket'
    | '/dramas'
    | '/entertainment'
    | '/movies'
    | '/news'
    | '/psl'
    | '/sports'
    | '/talk-of-the-town'
    | '/upcoming-dramas'
    | '/upcoming-movies'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/actors/$slug'
    | '/cricket/$slug'
    | '/cricket/players'
    | '/dramas/$slug'
    | '/movies/$slug'
    | '/news/$slug'
    | '/psl/$desk'
    | '/sports/football'
    | '/talk-of-the-town/$slug'
    | '/talk-of-the-town/personalities'
    | '/actors/'
    | '/bollywood/'
    | '/cricket/'
    | '/dramas/'
    | '/entertainment/'
    | '/movies/'
    | '/news/'
    | '/psl/'
    | '/sports/'
    | '/talk-of-the-town/'
    | '/upcoming-dramas/'
    | '/upcoming-movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdvertisingRoute: typeof AdvertisingRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ActorsSlugRoute: typeof ActorsSlugRoute
  CricketSlugRoute: typeof CricketSlugRoute
  CricketPlayersRoute: typeof CricketPlayersRoute
  DramasSlugRoute: typeof DramasSlugRoute
  MoviesSlugRoute: typeof MoviesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PslDeskRoute: typeof PslDeskRoute
  SportsFootballRoute: typeof SportsFootballRoute
  TalkOfTheTownSlugRoute: typeof TalkOfTheTownSlugRoute
  TalkOfTheTownPersonalitiesRoute: typeof TalkOfTheTownPersonalitiesRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
  BollywoodIndexRoute: typeof BollywoodIndexRoute
  CricketIndexRoute: typeof CricketIndexRoute
  DramasIndexRoute: typeof DramasIndexRoute
  EntertainmentIndexRoute: typeof EntertainmentIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PslIndexRoute: typeof PslIndexRoute
  SportsIndexRoute: typeof SportsIndexRoute
  TalkOfTheTownIndexRoute: typeof TalkOfTheTownIndexRoute
  UpcomingDramasIndexRoute: typeof UpcomingDramasIndexRoute
  UpcomingMoviesIndexRoute: typeof UpcomingMoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/actors'
      fullPath: '/actors/'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$slug': {
      id: '/actors/$slug'
      path: '/actors/$slug'
      fullPath: '/actors/$slug'
      preLoaderRoute: typeof ActorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollywood/': {
      id: '/bollywood/'
      path: '/bollywood'
      fullPath: '/bollywood/'
      preLoaderRoute: typeof BollywoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket/': {
      id: '/cricket/'
      path: '/cricket'
      fullPath: '/cricket/'
      preLoaderRoute: typeof CricketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket/$slug': {
      id: '/cricket/$slug'
      path: '/cricket/$slug'
      fullPath: '/cricket/$slug'
      preLoaderRoute: typeof CricketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket/players': {
      id: '/cricket/players'
      path: '/cricket/players'
      fullPath: '/cricket/players'
      preLoaderRoute: typeof CricketPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas/': {
      id: '/dramas/'
      path: '/dramas'
      fullPath: '/dramas/'
      preLoaderRoute: typeof DramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas/$slug': {
      id: '/dramas/$slug'
      path: '/dramas/$slug'
      fullPath: '/dramas/$slug'
      preLoaderRoute: typeof DramasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment/': {
      id: '/entertainment/'
      path: '/entertainment'
      fullPath: '/entertainment/'
      preLoaderRoute: typeof EntertainmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/movies/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psl/': {
      id: '/psl/'
      path: '/psl'
      fullPath: '/psl/'
      preLoaderRoute: typeof PslIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psl/$desk': {
      id: '/psl/$desk'
      path: '/psl/$desk'
      fullPath: '/psl/$desk'
      preLoaderRoute: typeof PslDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/football': {
      id: '/sports/football'
      path: '/sports/football'
      fullPath: '/sports/football'
      preLoaderRoute: typeof SportsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-of-the-town/': {
      id: '/talk-of-the-town/'
      path: '/talk-of-the-town'
      fullPath: '/talk-of-the-town/'
      preLoaderRoute: typeof TalkOfTheTownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-of-the-town/$slug': {
      id: '/talk-of-the-town/$slug'
      path: '/talk-of-the-town/$slug'
      fullPath: '/talk-of-the-town/$slug'
      preLoaderRoute: typeof TalkOfTheTownSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-of-the-town/personalities': {
      id: '/talk-of-the-town/personalities'
      path: '/talk-of-the-town/personalities'
      fullPath: '/talk-of-the-town/personalities'
      preLoaderRoute: typeof TalkOfTheTownPersonalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-dramas/': {
      id: '/upcoming-dramas/'
      path: '/upcoming-dramas'
      fullPath: '/upcoming-dramas/'
      preLoaderRoute: typeof UpcomingDramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-movies/': {
      id: '/upcoming-movies/'
      path: '/upcoming-movies'
      fullPath: '/upcoming-movies/'
      preLoaderRoute: typeof UpcomingMoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdvertisingRoute: AdvertisingRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ActorsSlugRoute: ActorsSlugRoute,
  CricketSlugRoute: CricketSlugRoute,
  CricketPlayersRoute: CricketPlayersRoute,
  DramasSlugRoute: DramasSlugRoute,
  MoviesSlugRoute: MoviesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  PslDeskRoute: PslDeskRoute,
  SportsFootballRoute: SportsFootballRoute,
  TalkOfTheTownSlugRoute: TalkOfTheTownSlugRoute,
  TalkOfTheTownPersonalitiesRoute: TalkOfTheTownPersonalitiesRoute,
  ActorsIndexRoute: ActorsIndexRoute,
  BollywoodIndexRoute: BollywoodIndexRoute,
  CricketIndexRoute: CricketIndexRoute,
  DramasIndexRoute: DramasIndexRoute,
  EntertainmentIndexRoute: EntertainmentIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PslIndexRoute: PslIndexRoute,
  SportsIndexRoute: SportsIndexRoute,
  TalkOfTheTownIndexRoute: TalkOfTheTownIndexRoute,
  UpcomingDramasIndexRoute: UpcomingDramasIndexRoute,
  UpcomingMoviesIndexRoute: UpcomingMoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
